### ISSUE TITLE
No issue but a Question

### ISSUE THREAD

**Issue by BlackChain02** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#67]
Is it possible to just Change the Background Picture?

**Comment by JustSomeRandomGuy3** [comment]
Yes. Change the following:

`--background: url('https://images.alphacoders.com/632/632525.png');`

To your own link. (`--background: url('*Insert link here.*');`

For example with my Alhaitham wallpaper (don't ask me why): `--background: url('https://images6.alphacoders.com/125/1252995.jpg')`

I can't try it since I'm using Vencord but if it works, let me know!

**Comment by BlackChain02** [comment]
Thank you very much it worked
